### PR TITLE
chall00 - gsanchez

### PR DESCRIPTION
**Pull request by GonzSanch**
Submitted function solution using memory, stupid hard way to review concepts

### CODE REVIEW

**Comment by GonzSanch** [comment]
In hv_rgb2hex function firts at all check valid values for rgb then create the returned char* allocating enough memory and started with '#' char and ended with Null. The rgb values to hex are procesed in an aux  function, this function takes the value, char* to fill and the index. If the value is greater than 16 the function will handle recursively else will add a zero before the value minor than 16.

**Comment by GonzSanch** [comment]
Probably I should replace "error" to NULL in L22 to handle error if rgb are negative or greater than 255..

**Comment by GonzSanch** [comment]
Changed return NULL instead "error", make flag static to work with recursivity and ajusted correct size of char* in allocation.

**Comment by anna-dominguez** [comment]
Too bad you've done a push after the limit hour...  Of what I can see you have done case of errors, protection of malloc. The function is failing on the output, you're missing the 0 written before a number.  I think you're close to the good answer !

**Pull request closed without merging**
