### PR TITLE
chall00-fulldemo

### PR DESCRIPTION
**Pull request by fulldemo13**
To solve it I converted the binary numbers to hexadecimal and I have been concatenating them all in the string "res". For this I used functions learned in 42. I paid attention to the limits of the numbers too.

### CODE REVIEW

**Comment by clafoutis42** [comment]
Good solution. However concatenating the string each time is really greedy with memory and execution time.  
A better solution would have been to allocate the memory for the all string and fill it later with the hexadecimal conversion.

**Comment by fulldemo13** [comment]
Thanks for the tips, next time will be better ;-)

**Comment by clafoutis42** [comment]
I just noticed that the filname was not of the format `xlogin` your PR will be reverted.

**Comment by fulldemo13** [comment]
Don't worry nobody is perfect, hahaha

**Pull request merged**
