### PR TITLE
Darodrig.c

### PR DESCRIPTION
**Pull request by d-r-e**

### CODE REVIEW

**Review by d-r-e — COMMENTED** [review]
Fixed '#' prefix

**Review by d-r-e — COMMENTED** [review]
Added a description of the code.

**Comment by clafoutis42** [comment]
This is a good solution, however you could have allocated directly the size of the wanted string, and modify it instead of using `strdup`.
Also you should have commented the solution in the pull request too.

**Comment by clafoutis42** [comment]
The file was not entered in the good subdirectory. Your PR will be reverted.

**Pull request merged**
